channels:
  # Define conda channels here.
  - conda-forge

dependencies:
  # Define conda packages here.
  # If available, always prefer the conda version of a package.
  # Installation will be faster and more efficient.
  # https://anaconda.org/search
  - python=3.9.13            # https://pyreadiness.org/3.9/ 

  # Load Firefox and corresponding driver from conda-forge.
  - firefox=113.0            # https://anaconda.org/conda-forge/firefox

  - pip=22.3.1               # https://pip.pypa.io/en/stable/news/
  - pip:
      # Define pip packages here.
      # https://pypi.org/
      - rpaframework==22.5.3 # https://rpaframework.org/releasenotes.html
